// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh9arHqqxT0bwOZQKcnTciBHifip2f9iM',
    appId: '1:299194253766:web:8b39624fdf03018addb2c7',
    messagingSenderId: '299194253766',
    projectId: 'whatsapp-b70ec',
    authDomain: 'whatsapp-b70ec.firebaseapp.com',
    storageBucket: 'whatsapp-b70ec.appspot.com',
    measurementId: 'G-MFJJTPWS58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu1wQkqjjNCsOhVXVVVc5VjQ7i66cXtKc',
    appId: '1:299194253766:android:864856ff59002469ddb2c7',
    messagingSenderId: '299194253766',
    projectId: 'whatsapp-b70ec',
    storageBucket: 'whatsapp-b70ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0xqW8RZNakSJwCF8Kfb_sxRl6c5tzmsU',
    appId: '1:299194253766:ios:6739192d93ddf4c6ddb2c7',
    messagingSenderId: '299194253766',
    projectId: 'whatsapp-b70ec',
    storageBucket: 'whatsapp-b70ec.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0xqW8RZNakSJwCF8Kfb_sxRl6c5tzmsU',
    appId: '1:299194253766:ios:063ca1440f427d29ddb2c7',
    messagingSenderId: '299194253766',
    projectId: 'whatsapp-b70ec',
    storageBucket: 'whatsapp-b70ec.appspot.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
